//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public long Id { get; set; }
        public string cCod { get; set; }
        public string cNome { get; set; }
        public string cUF { get; set; }
        public string nCodIBGE { get; set; }
        public Nullable<int> nCodSIAFI { get; set; }
    }
}
