//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Livro_Caixa
    {
        public long Id { get; set; }
        public long Id_livro { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public string documento { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
        public Nullable<long> Id_empresa { get; set; }
        public Nullable<long> Id_filial { get; set; }
        public Nullable<long> Id_parcela { get; set; }
        public Nullable<long> Id_contaspagar { get; set; }
    
        public virtual Livro_Caixa livro_caixa { get; set; }
        public virtual Empresa empresa { get; set; }
        public virtual Filial filial { get; set; }
        public virtual Pedido_Otica_Parcelas pedido_otica_parcelas { get; set; }
        public virtual Contas_Pagar contas_pagar { get; set; }
    }
}
