//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Otica_Parcelas : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido_Otica_Parcelas()
        {
            this.item_livro_caixa = new HashSet<Item_Livro_Caixa>();
        }
    
        public long Id { get; set; }
        public long Id_pedido_otica { get; set; }
        public Nullable<int> numero_parcela { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> percentual { get; set; }
        public string data_vencimento { get; set; }
        public Nullable<int> quantidade_dias { get; set; }
        public string pago { get; set; }
        public string usuario_pagamento { get; set; }
        public Nullable<System.DateTime> data_pagamento { get; set; }
        public string forma_pagamento { get; set; }
    
        public virtual Pedido_Otica pedido_otica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Livro_Caixa> item_livro_caixa { get; set; }
    }
}
